### PR TITLE
Optimization/move to zenkit

### PR DESCRIPTION
**Pull request by JaXt0r**
It is done!

# To test
1. Start game with Production Feature flags and spawn Bloodwyn + Logs (see picture)
image
2. Start game and play 
3. Look for
    4. Crashes - If not, we're good
    5. Some other weird stuff or errors (Not expected)

# Checklist

## Scene
* [x] FeatureFlags reverted to right value

# Testing
* [x] Merged _main_ into this branch and tested with the latest features
* [x] Tested with PCVR
* [x] Tested with Pico / Quest

## Dependencies
* [x] If libphoenix-shared.dll is changed, .so is also changed

### CODE REVIEW

**Comment by Tyroonis** [comment]
Main menu starts

Nothing happens when I click on start

```ArgumentException: Destination scene is not valid
UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene (UnityEngine.GameObject go, UnityEngine.SceneManagement.Scene scene) (at <30adf90198bc4c4b83910c6fb1877998>:0)
GVR.Manager.GvrSceneManager.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs:178)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <30adf90198bc4c4b83910c6fb1877998>:0)```

**Comment by JaXt0r** [comment]
image

**Comment by JaXt0r** [comment]
image

**Comment by Tyroonis** [comment]
Android not work at the moment
[gothicvr_log.txt](https://github.com/GothicVRProject/GothicVR/files/13823638/gothicvr_log.txt)

**Review by JucanAndreiDaniel — APPROVED** [review]
Took a quick look at the code, seems fine since it's mostly api changes (and sound decoding inclusion from PxCs)
Tested on quest 2, works flawlessly

**Pull request merged**
